### ISSUE TITLE
LIST OF BUGS AND INSECTS AND STUFF

### ISSUE THREAD

**Issue by asprout** [CinWu/peep#2]
- ~~ValueError: View function did not return a response when confirm emails/passwords do not match up~~
- location search does not work
- ~~welcome message needs better formatting~~
- ~~sidebar does not really have a function and also does not work...~~
- tag formatting?
- ~~create event button should be on the bottom~~
- ~~should order events from nearest to farthest (in terms of date)~~
- forum and/or private messaging system
- ~~add created events to events attending~~
- ~~sidebar does not always display information of correct user~~
- ~~when you click on profile, have it display a list of the events the person created/is attending?~~
- unicode error when registering
- maps display wrong location
- ~~request to join button still shows for events that you are attending but did not make~~

**Comment by TLiang518** [comment]
~~Bottom bar needs to be static?~~
~~Sidebar needs to be made loggedin-only~~
Maps need to show only when viewing event
Browse needs to be implemented
~~Events Pending, Mesasges, Events Created - null message placement~~

**Comment by TLiang518** [comment]
Edit Event/Profile Feature
Can't Approve/Reject more than once in a row
